import type { TopicSummary } from "@/lib/types";

function BulletSection({ title, items }: { title: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <div>
      <h3 className="font-semibold">{title}</h3>
      <ul className="mt-1 list-disc space-y-1 pl-5 text-sm">
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

export function TopicSummaryView({ summary }: { summary: TopicSummary }) {
  return (
    <section aria-labelledby="summary-heading" className="space-y-4">
      <div>
        <div className="flex items-center gap-2">
          <h2 id="summary-heading" className="text-lg font-semibold">
            Summary
          </h2>
          <span className="bg-muted text-muted-foreground rounded px-1.5 py-0.5 text-xs font-medium">
            AI-generated
          </span>
        </div>
        <p className="mt-1">{summary.summary}</p>
      </div>

      <BulletSection title="Points of agreement" items={summary.agreements} />
      <BulletSection
        title="Points of disagreement"
        items={summary.disagreements}
      />
      <BulletSection title="Open questions" items={summary.openQuestions} />

      <p className="text-muted-foreground text-xs">
        This summary was generated by AI based on the {summary.sourceArticleIds.length}{" "}
        source article{summary.sourceArticleIds.length === 1 ? "" : "s"} listed
        below. It is not a substitute for reading the original reporting.
      </p>
    </section>
  );
}
